name: first job
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print hello world
        run: echo "hello world"
      - name: print bye world
        run: echo "done bye"
      - name: run multiple commands
        run: |
            echo "First output"
            echo "Second output"
    
